from openrec.tf1.legacy.modules.interactions.interaction import Interaction
from openrec.tf1.legacy.modules.interactions.pairwise_log import PairwiseLog
from openrec.tf1.legacy.modules.interactions.pairwise_hinge import PairwiseHinge
from openrec.tf1.legacy.modules.interactions.ns_log import NsLog
from openrec.tf1.legacy.modules.interactions.pointwise_ge_ce import PointwiseGeCE
from openrec.tf1.legacy.modules.interactions.pointwise_mlp_ce import PointwiseMLPCE
from openrec.tf1.legacy.modules.interactions.pairwise_eu_dist import PairwiseEuDist
from openrec.tf1.legacy.modules.interactions.ns_eu_dist import NSEuDist
from openrec.tf1.legacy.modules.interactions.pointwise_ge_mlp_ce import PointwiseGeMLPCE
from openrec.tf1.legacy.modules.interactions.pointwise_mse import PointwiseMSE
