from openrec.tf1.legacy.recommenders.recommender import Recommender
from openrec.tf1.legacy.recommenders.bpr import BPR
from openrec.tf1.legacy.recommenders.pmf import PMF
from openrec.tf1.legacy.recommenders.nbpr import NBPR
from openrec.tf1.legacy.recommenders.concat_visual_bpr import ConcatVisualBPR
from openrec.tf1.legacy.recommenders.visual_pmf import VisualPMF
from openrec.tf1.legacy.recommenders.cdl import CDL
from openrec.tf1.legacy.recommenders.cml import CML
from openrec.tf1.legacy.recommenders.wcml import WCML
from openrec.tf1.legacy.recommenders.visual_bpr import VisualBPR
from openrec.tf1.legacy.recommenders.visual_cml import VisualCML
from openrec.tf1.legacy.recommenders.gmf import GMF
from openrec.tf1.legacy.recommenders.visual_gmf import VisualGMF
from openrec.tf1.legacy.recommenders.user_pmf import UserPMF
from openrec.tf1.legacy.recommenders.user_visual_pmf import UserVisualPMF
from openrec.tf1.legacy.recommenders.itr_mlp import ItrMLP
